---
apiVersion: v1
kind: Service
metadata:
  name: APPLICATION
spec:
  selector:
    app: APPLICATION
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: EXPOSEPORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPLICATION
  labels:
    app: APPLICATION
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPLICATION
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        app: APPLICATION
    spec:
      containers:
        - name: APPLICATION
          image: DOCKER/NAMESPACE/APPLICATION:TAG
          command: [COMMAND]
          args: [ARGS]
          ports:
            - containerPort: 80
          imagePullPolicy: Always
#          volumeMounts:
#            - name: logs
#              mountPath: /logs
#            - name: data
#              mountPath: /data
#            - name: files
#              mountPath: /files
      imagePullSecrets:
        - name: regcred
#      volumes:
#        - name: logs
#          persistentVolumeClaim:
#            claimName: PVC_LOGS
#        - name: data
#          persistentVolumeClaim:
#            claimName: PVC_DATA